### ISSUE TITLE
MultiControlledMixin improvements

### ISSUE THREAD

**Issue by Eenae** [mixbytes/icoplate_ico#1]
- [x] нужно иметь возможность делать detachControllersForever автоматически (в конце ико), т.е. со стороны контроллера
- [x] isController - может быть constant
- [x] isController - определенно нужно проверить потребление газа. Скорее всего четко будет видно, что нужен mapping. Кроме того предлагаю снять или заметно повысить c_MaxControllers
- [x] getControllers FYI можно сразу return m_controllers
- [x] detachController() - delete не освобождает "слот", а просто обнуляет, т.е. напр. в `addController` по-прежнему будет срабатывать `require(m_controllers.length < c_MaxControllers);`, если до detach уже были заполнены все контроллеры. С переходом на mapping проблема уйдет, пишу на будущее ради понимания проблемы

**Comment by suffrage** [comment]
- detachControllersForever - может выполняться от Owner и от Controller
Добавил новый модификатор onlyControllersOrOwners
- Повысил значение MaxControllers до 255
Сделал его функцией возвращающей константу, для того чтобы можно было переопределить в Хелпере
- getControllers - использовалась только в тестах, перенес в хелпер
- Сделал корретное удаление элемента из массива. Стоит ли так однозначно переходить на mapping

**Comment by Eenae** [comment]
> Стоит ли так однозначно переходить на mapping

а какой расход газа на isController при 5 контроллерах в обоих случаях?

**Comment by suffrage** [comment]
Как проверить использование газа конкретной функцией?

**Comment by karbachinsky** [comment]
про потребление газа для isController.  В контексте малых чисел, hash избыточен в нормальных языках.  тут же ситуациия такая:
Если используем Mapping вместо Array, то создание контракта потребялет чуть меньше газа, а проверка больше.

Если используем Iterable Mapping как в multiowned - то профита и того становится меньше.

В нашем контексте, когда у нас всего 3 контроллера за историю всего ICO - предлагаю оставить так.

**Comment by Eenae** [comment]
Ок, тогда MaxControllers поднимать нельзя, и нужно откомментить, вышеописанное в код, добавив, что на больших числах - нужно отдельно тестировать потребление газа.

**Comment by suffrage** [comment]
@Eenae поставлю 10 тогда, должно хватить

**Comment by Eenae** [comment]
ок
