### ISSUE TITLE
incorrect condition

### ISSUE THREAD

**Issue by quantum13** [mixbytes/icoplate_ico#11]
https://github.com/mixbytes/icoplate_ico/blob/00aa8fdf2e9a21250814f4e9e1f4d1b75fb98f45/contracts/ICOPICO.sol#L141

in simpleCrowdsale condition:
```require(getCurrentTime() >= getStartTime() || ! mustApplyTimeCheck(investor, payment) /* for final check */);```

so non-owner satisfies this and can contribute before start date

**Comment by Eenae** [comment]
> we have user collision and investor1 is actually the same user as owner1.

Yep, we have this collision on purpose to catch bugs in case owner decided for some reason (e.g. to test) to send some money into contract.
