### ISSUE TITLE
PLTToken.burn

### ISSUE THREAD

**Issue by Eenae** [mixbytes/icoplate_ico#2]
В burn нужно добавить также событие Transfer, чтобы клиенты (кошельки) понимали, что баланс владельца изменился

**Comment by suffrage** [comment]
а что внутри события нужно передать?

**Comment by suffrage** [comment]
Transfer(this, _to, _amount);

**Comment by Eenae** [comment]
`Transfer(_to, this, _amount);` - токены якобы вернулись обратно

**Comment by Eenae** [comment]
я бы кстати аргумент burn назвал не _to а _from

**Comment by suffrage** [comment]
@Eenae Проверь, пожалуйста, и закрой

**Comment by karbachinsky** [comment]
@suffrage   Идея _to в том. что ты сжигаешь токены "У кого-то", т.е. это направление в "инвестора", а не в обратную сторону "От"
