### ISSUE TITLE
ICOPPreSale

### ISSUE THREAD

**Issue by Eenae** [mixbytes/icoplate_ico#3]
- [x] не вижу где переопределен callback платежей через аналитику iaOnInvested - эти инвестиции не будут учтены
- [x] owner не сможет сделать тестовую инвестицию до наступления времени начала сейла
- [x] а что в итоге с заменой в SimpleCrowdsaleBase MintableMultiownedToken на интерфейс mintable токена?
- [x] вам понадобится доступ к createMorePaymentChannelsInternal - нужно сделать метод-обертку и подумать кому дать права

**Comment by karbachinsky** [comment]
Про заменту на Mintable токен - я вымержил ветку взад. Не получалось реализовать через нее.

**Comment by karbachinsky** [comment]
2. https://github.com/mixbytes/icoplate_ico/commit/b66964f6732fccbbcf3b927ef559c0091f545a6f

**Comment by karbachinsky** [comment]
1. 4.  Пофиксил, еще прогоним тесты через utest/Crowdsale.js чтобы проверить  
https://github.com/mixbytes/icoplate_ico/commit/d9680809bad00f087a7479189268198dabf6f248
